### ISSUE TITLE
AVX doesn't compile

### ISSUE THREAD

**Issue by Ptomaine** [avaneev/avir#10]
Hello again, Aleksey :)

I tried to compile with the AVX optimized version of float8 data type, but failed.
MinGW/GCC throws the error:
```
error: inlining failed in call to always_inline '__m256 _mm256_set1_ps(float)': target specific option mismatch                            1310 | _mm256_set1_ps (float __A)
                                                                | ^~~~~~~~~~~~~~                                                                                                                                                                                          
avir_float8_avx.h:50:26: note: called from here
50 |   : value( _mm256_set1_ps( s ))
```

SSE compiles good.
For AVX, I've tried all posible compiler options, but failed.
Do you know how to fix it?

**Comment by avaneev** [comment]
I'm unaware how to fis this issue, this issue does not happen in Intel C++ compiler. You may try to move from initializer to body:
value = _mm256_set1_ps( s );

**Comment by jart** [comment]
@Ptomaine By default GCC assumes it's building a binary for the AMD K8. Try passing the `-march=native` flag to the compiler. It enables all the various flags like `-mavx2` that your host CPU happens to supports.
