### ISSUE TITLE
Question - Usage Example

### ISSUE THREAD

**Issue by mohsenomidi** [avaneev/avir#11]
Would you please provide simple main complete example to resize the Image ?
I can not find complete usage code for this library, i just do below steps but not succeed.

1- open original Image
2- resize by library
3- save to new file 

in step 2 i dont know how should i set the output buffer size then i set it to original file size, 
the code below has exception (segmentation fault) after  `ImageResizer.resizeImage`
Successfull Compile by G++ Version :
`g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
`

Complie Command:
`g++ main.cpp -o run
`

Runtime Error:
`Segmentation fault (core dumped)
`

Source Code:
```
#include <iostream>
#include <string.h>
#include "avir.h"
#include <fstream>


inline void setFileContent(const std::string &pFileName, const std::string &pFileContent)
{
    std::ofstream fileStreamWrite(pFileName);
    fileStreamWrite << pFileContent;
    fileStreamWrite.close();
}

inline std::string getFileContent(const std::string &pFileName)
{
    std::ifstream fileStreamRead(pFileName);
    std::string fileContents((std::istreambuf_iterator<char>(fileStreamRead)),
            std::istreambuf_iterator<char>());
    return fileContents;
}


int main()
{


    std::string pOriginalImage = getFileContent("test.jpg");

    char cstr[pOriginalImage.size() + 1];
    std::copy(pOriginalImage.begin(), pOriginalImage.end(), cstr);
    cstr[pOriginalImage.size()] = '\0';
    
    uint8_t * inputBuffer = new uint8_t [pOriginalImage.size() + 1];
    inputBuffer = reinterpret_cast<uint8_t *>(cstr);

    uint8_t * outputBuffer = new uint8_t [pOriginalImage.size() + 1];

    avir :: CImageResizer<> ImageResizer( 8 );
    ImageResizer.resizeImage( inputBuffer, 640, 480, 0, outputBuffer, 320, 240, 3, 0 );
    std::string OutPut(reinterpret_cast< char const * >(outputBuffer));
    setFileContent("resize.jpg",OutPut);
   return 0;
}
```

**Comment by avaneev** [comment]
Your request looks like a very basic programming question. Sorry, I can't provide assistance for such case, I suggest you to study arrays and buffers and how images are organized first.

**Comment by mohsenomidi** [comment]
Yes it is VERY Basic question about using your library, it is not related to programming, most of well documented libraries provide the tutorial, and complete example to show how you can use it, if i have complete knowledge about the image and processing images and image buffers, i could write my own image lib to handle my requirements, and never refer to the Libs, there are lots of open source libraries can handle this smoothly and without needs in-depth information about the library itself, because most of people just want to use it and they are not expert in that particular concept.

Just for more information for other people need the library for advanced and basic image processing, may they need examples and how to manuals, like me with very very basic programming knowledge 😉 and also they don't need extra info about the structure of internal library structure, could use these opensource Libs that noted below:

[OpenCV - Well Documented, with complete example usage](https://github.com/opencv/opencv) 

[imlib2 - Well Documented, with complete example usage ](url)

[CImg - Well Documented, with complete example usage](https://github.com/dtschump/CImg)

[Boost/GLI - if you are using boost it can be helpful ](https://github.com/boostorg/gil)

[ImageMagic ](https://imagemagick.org/index.php)

[GraphicsMagick](http://www.graphicsmagick.org/index.html)

[Intel - IPP ](https://software.intel.com/en-us/ipp)

And the other libraries you can find in GitHub that can handle this task without involving you to deal with low level image data and buffers, etc...

**Comment by avaneev** [comment]
Sorry, but you are a bit misinformed - AVIR's interface is as simple as possible, much easier to use than most libraries you've noticed. I think you simply lack a very basic understanding how buffers work, how much size you need to allocate, how image sizes correspond to buffer sizes. Without this knowledge you won't be able to use any library you've mentioned.

**Comment by mohsenomidi** [comment]
I don't have any  argument in this regard but for clarification about your sentence that mentioned above that slandered me to provide the "misinformed" i will share the OpenCV example to resize and edit photos below for you to show how they work without difficultly, 
and also it is not just related to me you can see the [The Problem for many people that using this Lib](https://github.com/avaneev/avir/issues/1)

In the other hand, i think this argument takes more time from you and me to write many sentence to prove our understanding or trying to help each other, you can easily provide one basic high level main file for people like me ( by assuming that they don't have any knowledge about buffers or other staffs) to show how the you can use the library. it is very simple, easy and will good for your lib and many people can use it for now your library takes about 70 star and 10 watcher, if it was easy in could take more scores than this numbers.

**Any way, with all due respect to your attitude and viewpoint on this matter, I think I received the full answer and hope you will always be successful and successful.**

Simple Example To Show How to Open Edit Resize Photos in Open CV: 


```
#include "opencv2\highgui.hpp"
#include "opencv2\imgproc.hpp"
#include "opencv2\video\background_segm.hpp"
#include "opencv2\video\tracking.hpp"

using namespace cv;
using namespace std;

int main(int argc, const char** argv)
{
  //  Load the image from file
 Mat LoadedImage;
 // Just loaded image Lenna.png from project dir to LoadedImage Mat
 LoadedImage = imread("Lenna.png", IMREAD_COLOR);
 //I would like to visualize Mat step by step to see the result immediately.
 // Show what is in the Mat after load
 namedWindow("Step 1 image loaded", WINDOW_AUTOSIZE);
 imshow("Step 1 image loaded", LoadedImage);
 waitKey(1000);
 // Same the result from LoadedImage to Step1.JPG
 imwrite("Step1.JPG", LoadedImage);
 
// Saved Image looks like original :)
// You can load colored image directly as gray scale
 LoadedImage = imread("Lenna.png", CV_LOAD_IMAGE_GRAYSCALE);
  // Show what is in the Mat after load
 namedWindow("Step 2 gray image loaded", WINDOW_AUTOSIZE);
 imshow("Step 2 gray image loaded", LoadedImage);
        // Show the result for the longer time. 
        // If you want to see video frames in high rates in the loop jist put here waitKey(20). 
 waitKey(1000);

 // Same the result from LoadedImage to Step2.JPG
 imwrite("Step2.JPG", LoadedImage);
  //  Basic resize and rescale 
 //
 // Resize LoadedImage and save the result to same Mat loaded Image.
 // You can also resize( loadedImage, Result, ..... )

 // Load again source images
 LoadedImage = imread("Lenna.png", IMREAD_COLOR);
 //You can resize to any size you want Size(width,heigth)
 resize(LoadedImage, LoadedImage, Size(100, 100));
 
 // Vizualization
 namedWindow("Step 3 image resize", WINDOW_AUTOSIZE);
 imshow("Step 3 image resize", LoadedImage);
 waitKey(1000);

 // Yes it is smaller than source. 100x100 image
  //Save above image to Step3.jpg 
 imwrite("Step3.JPG", LoadedImage);
 LoadedImage = imread("Lenna.png", IMREAD_COLOR);

 // Better is resize based on ratio of width and heigth
 // Width and heigth are 2 times smaller than original source image
 // result will be saved into same mat. If you are confused by this. 
 // You can try to modify the code and add MAT outputImage and dysplay it. 
 //!! cols number of collumn of the image mat. and rows are rows
// cols and rows are same ase width and heigth
 resize(LoadedImage, LoadedImage, Size(LoadedImage.cols/2, LoadedImage.rows/2));
                          
 // Vizualization
 namedWindow("Step 4 image resize better", WINDOW_AUTOSIZE);
 imshow("Step 4 image resize better", LoadedImage);
 waitKey(1000);
  // Save
 imwrite("Step4.JPG", LoadedImage); 
 //All the steps are saved in Step1 Step
}
```

**Comment by hadeda** [comment]
I cannot speak for others, but I do have a good working knowledge of buffers, yet I am having the same difficulty as Moshen.  Your software may well be very easy to use, but in the absence of an example to show us how to use it, we will never know.

**Comment by avaneev** [comment]
Well, a lot of libraries offer you "frontend" for image loading and manipulation where you do not even need the knowledge how images are composed and physically stored. AVIR requires you to have low-level knowledge how image buffers work. Each image consists of pixels - 3 elements usually, RGB. Then image buffer consists of scanlines, each scanline consists of pixels. So, 640x480 3-channel 8-bit image image consists of 640*480*3 elements of type `uint8_t`.

Take a look at this Issue: https://github.com/avaneev/avir/issues/8 People there do not have such issues like you have, they've even delved in a very advanced area of multi-threaded usage of AVIR, and succeeded after all.

You do really need to up your C++ and image processing knowledge a bit to use AVIR.

**Comment by hadeda** [comment]
Driving from my house to my work is really very easy - if you know how, or if you figure it out.  If you don't know, I do not criticise your ability to drive - I simply show you the directions.  A simple example program is like a map to a driver - it makes it easy for people to use your software, or to evaluate from the example usage if your software is suitable for their needs.

**Comment by virtualenv** [comment]
After reading these, and not seeing any solution, here is my try, apperantly it worked (using opencv to read and write).

#include "avir.h"
#include <opencv2/opencv.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/videoio.hpp>

int main()
{
	cv::Mat InBuffer;
	uint8_t * inputBuffer, * outputBuffer;
	int w, h, c;
	avir::CImageResizer<> ImageResizer(8);

	InBuffer = cv::imread("original.jpg");
	w = InBuffer.cols;
	h = InBuffer.rows;
	c = InBuffer.channels();
	inputBuffer = new uint8_t[w * h * c];
	inputBuffer = InBuffer.data;
	outputBuffer = new uint8_t[(w * 2) * (h * 2) * c];// deseried size 868x1292
	ImageResizer.resizeImage(inputBuffer, w, h, 0, outputBuffer, w * 2, h * 2, c, 0);
	cv::Mat OutBuffer(h*2, w*2, CV_8UC3, outputBuffer);
	cv::imwrite("resize.jpg", OutBuffer);

	return 0;
}

**Comment by avaneev** [comment]
Thanks for the example.

**Comment by hadeda** [comment]
This example is very helpful - thank you for it.

**Comment by virtualenv** [comment]
> Thanks for the example.



> This example is very helpful - thank you for it.

My pleasure!

**Comment by virtualenv** [comment]
> Thanks for the example.

Sir, thank you for this great API!

**Comment by wahlberg82** [comment]
Thanks a lot for the example @virtualenv, it helps a lot!

**Comment by virtualenv** [comment]
> Thanks a lot for the example @virtualenv, it helps a lot!

My pleasure!

**Comment by Demolishun** [comment]
I concur, a set of examples showing buffer construction in the docs would be very helpful.  I am trying to feed it a buffer with ARGB pixels and I cannot tell what it is choking on.  I need to step through the code and see where it is going out of bounds.  I don't see anything in the docs that describes if this library can handle alpha channels.  I get it you have to set the parameter to 4 instead of 3 indicating the number of bytes per pixel.  But it doesn't say if the pixels need to be in RGBA or ARGB.  Maybe it doesn't matter.

**Comment by avaneev** [comment]
RGBA or ARGB, it does not matter. Only 4 for channel count matters.

**Comment by Demolishun** [comment]
Thank you!

**Comment by Demolishun** [comment]
@avaneev is the idea of templatizing the buffers so that you don't assume a byte per ElCountIO?  I think I was thinking the input and output required a pointer to a buffer with bytes.  However, my buffer pointer was QRgb which is a 32 bit int.  So I need to reinterpret_cast<uchar*>(QRgb*) to feed to the resize function.  It now makes sense which is was crashing.  It was treating each ElCountIO as a 32 bit int instead of an 8 bit char.

**Comment by avaneev** [comment]
Yeah, you have to be more attentive when reading function descriptions. Templating the buffer element allows to have the same code to resize 8-, 16-bit and float buffers.

**Comment by Demolishun** [comment]
Your api description needs work.  
I was able to get it to scale image last night.  I have been directly comparing the output to the scaling function from here:
https://doc.qt.io/qt-5/qimage.html#scaled
I am not seeing a big difference in output for the different scaling resolutions.  I am using this setting on the scaler from Qt:
Qt::SmoothTransformation | 1 | The resulting image is transformed using bilinear filtering.

When I tried some of the other settings of avir some things looked slightly better, but then those introduced some strange shadowing/outline effects in the transition from light to dark.  I saw this quite a bit on CImageResizerParamsUltra.  Is that the ringing you talk about in your code comments?

**Comment by avaneev** [comment]
Yes, "Ultra" produces ringing/outline. If you do not see a difference between AVIR and bilinear filtering, I can't help or argue. Working with images requires quite a bit of experience to understand the differences and seeing the bigger picture.
