### ISSUE TITLE
Resizing of an image in a 'float' array representation damages the image

### ISSUE THREAD

**Issue by yurivict** [avaneev/avir#12]
In this testcase https://people.freebsd.org/~yuri/avir-testcase.tgz the scaled image that was represented as floats has green and pink pixels that weren't present in the original image.
Scaling in uint8 doesn't have this problem.

Please uncomment typedefs in the attached testcase to reproduce damaged and undamaged output cases.

**Comment by avaneev** [comment]
Please send a link to zip - I can't open this tgz file, it is seemingly unsupported.

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/avir-testcase.zip

**Comment by avaneev** [comment]
I've made an independent test - and there is I think a problem with your PNG writer, it does not clip float values correctly above 1 and below 0.

**Comment by yurivict** [comment]
> problem with your PNG writer

You should clip the values, because a valid range is 0,0 .. 1.0, so that you produce invalid values in the resized images.

**Comment by avaneev** [comment]
No, it does not work that way for floats. If you need clipped values, use uint8_t* output buffer, AVIR will apply clipping automatically.
