### ISSUE TITLE
is there a detailed description of the algorithm?

### ISSUE THREAD

**Issue by JVision** [avaneev/avir#13]
This looks like a great method. is there any document that define the method clearly? or as it implies that the method implements a 18-tap windowed sinc interpolation?

would appreicate if there are graphs/illustrations showing the detailed method.

**Comment by avaneev** [comment]
GitHub pages describe elements of the method pretty clearly - 2-times preliminary upsizing is a staple of the method. I have no plans nor experience to write it all in "scientific" manner. The method works, sources are available - that's enough, if somebody wants to extend the method, all information is available already.
