### ISSUE TITLE
add --algparams=ultra

### ISSUE THREAD

**Issue by virtualenv** [avaneev/avir#16]
Sir, thank you for such a great API.
I was wondering how to add --algparams=ultra to the code, I was able to add to the command line only.

Thank you.

**Comment by virtualenv** [comment]
Did mean to close it...

**Comment by avaneev** [comment]
avir :: CImageResizer<> ImageResizer( 8, 0, avir :: CImageResizerParamsUltra() );

**Comment by virtualenv** [comment]
Thank you sir!!!
