### ISSUE TITLE
Few questions about the avir algorithm

### ISSUE THREAD

**Issue by Optimizer0** [avaneev/avir#17]
First of all, thank you so much for giving us this incredible library. I can't believe it's free and open-source considering it's top-notch quality. Output results look amazing, speed is mind-blowing and the interface is as simple as it can get. Again can't thank you enough for this.

I'm creating an Image Processor for android. Tho the library itself is amazing, I would like to implement my own version of the algorithm to be used in my application. Mainly for the following reasons.

1. I won't be using most of the extra features offered. I just need to downsize a 8 bit 4 channel image. So hopefully I will be able to cut down the size of the library.
2. As this is a mobile application, I would like to squeeze out the every bit of performance I can. Implementing my own version will allow me to do optimizations unique to my app environment.
3. I already have a resizing engine. So I would like this algorithm to be seamlessly integrated into it. 

So my questions are,

1) Do you have any specification at the moment, that I can use to implement it?
2) Do you think I'll be able to cut off the size by a considerable amount by removing unused features such as (16,24 bit / sRGB featues)
3) Do I have your permission to implement it into my application? You of course will be credited properly both in docs and the application itself.

**Comment by avaneev** [comment]
No, I have no specifications on the changes, do them at your own risk. You can safely remove all `if( ElCount == 1..2..3 )` branches if you plan to use 4 channels only. Removing gamma correction won't reduce code size much. You can modify the code as you wish, only the originator (me) should me mentioned.

**Comment by Optimizer0** [comment]
cool
