### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by b005t3r** [avaneev/avir#18]
Not really an issue, but it would be great to have any performance numbers listed in the description/readme. I just tried to use it for real-time processing and, well, it's not fast :)

**Comment by avaneev** [comment]
For real-time please use LANCIR.

**Comment by avaneev** [comment]
Performance number is specified which does suggest it can't be used in real-time.

**Comment by b005t3r** [comment]
Couldn't find any performance data here, on GitHub. Also tried LANCIR, not significantly faster (but, as I said, it's not a complain, I understand it's not made with real-time processing in mind).

**Comment by avaneev** [comment]
"Preliminary tests show that this library (compiled with Intel C++ Compiler 18.2 with AVX2 instructions enabled, without explicit SIMD resizing code) can resize 8-bit RGB 5184x3456 (17.9 Mpixel) 3-channel image down to 1920x1280 (2.5 Mpixel) image in 245 milliseconds, utilizing a single thread, on Intel Core i7-7700K processor-based system without overclocking. This scales down to 74 milliseconds if 8 threads are utilized."
