### ISSUE TITLE
optimize on ARM (A53 A73)，can realize？

### ISSUE THREAD

**Issue by jcyhcs** [avaneev/avir#19]
first of all, your code is very excellent, i want to use your code , let it run on ARM CPU, for example, A53, but it is very SLOW!, so ,can you optimize this code on ARM CPU?   Best My Regards!

**Comment by avaneev** [comment]
It's a generic code, it cannot be made faster. If you do not need maximal quality you may try LancIR resizer.

**Comment by jcyhcs** [comment]
ok,well, i just test the LANCIR resizer, an 1920*1080 pic , resize upsample 2X, it cost 14255ms!, i test the same pic use opencv4.3 resize function with Lanczos method, is just cost 1598ms!,  so  can you optimize your LancIR method? my betst regards!

**Comment by jcyhcs** [comment]
by the way , i test  on ARM A53 cpu

**Comment by avaneev** [comment]
I think ARM is not very good at memory-intensive operations. I cannot optimize LancIR. OpenCV probably uses videocard features.
