### ISSUE TITLE
Ram limit of the win32 exe reach for very big image

### ISSUE THREAD

**Issue by NateBeauPro** [avaneev/avir#21]
While testing the limit of this app (exe, not the C++ code), I noticed that : for one (and not for an other) of my big size png image at 14400x20656 (119MB vs 97,8MB), if I try to resize with scale 4 (=>3600x5164) the exe crash without error reported. After some reseach on this issue, I tried to "patch" the exe with 4GB Patch (https://ntcore.com/?page_id=371) and it no longer crashes.
I don't know if this is normal, but i report it just in case

**Comment by avaneev** [comment]
Yes, that's expected for 32-bit execs. Your input image does seem to require 1.5GB internally. The "exe" is presented for quick demonstration only, it's not a defining feature of the library.

**Comment by avaneev** [comment]
@NateBeauPro Hi! I've added Win64 binary of "imageresize", should have no issues with large images.

**Comment by NateBeauPro** [comment]
Thank you for adding this feature !
