### ISSUE TITLE
Example for using with the Qt library - QImage 

### ISSUE THREAD

**Issue by dzucchetti** [avaneev/avir#22]
Thank for sharing the code.
I’m using the Qt Library and QImage class. I would try to see if ImageResizer.resizeImage is better than the QImage:scaled https://doc.qt.io/qt-5/qimage.html#scaled.
I have no idea on how image format and buffers works. 
I wonder if it is possible to use the library with the QImage format and if there are examples for 
* using an existing QImage, 
* creating a buffer and resizing with the ImageResizer.resizeImage 
* converting the result back to QImage.

Speed is not an issue.

**Comment by avaneev** [comment]
Sorry, I'm not familiar with Qt. I'll quote this from the project page:
"AVIR works with header-less "raw" image buffers. If you are not too familiar with the low-level "packed interleaved" image storage format, the InBuf is expected to be w*h*c elements in size, where w and h is the width and the height of the image in pixels, respectively, and c is the number of color channels in the image. In the example above, the size of the InBuf is 640*480*3=921600 elements. If you are working with 8-bit images, the buffer and the elements should have the uint8_t* type; if you are working with 16-bit images, they should have the uint16_t* type. Note that when processing 16-bit images, the value of 16 should be used in resizer's constructor. AVIR's algorithm does not discern between channel packing order (RGBA, ARGB, BGRA, etc.), so if the BGRA ordered elements were passed to it, the result will be also BGRA."

**Comment by dzucchetti** [comment]
From the Qt documentation I see they support quite a lot of format https://doc.qt.io/qt-5/qimage.html#image-formats and that each format has their specific storage specification. 
In my case it use the QImage::Format_RGB32, the image is stored using a 32-bit RGB format (0xffRRGGBB).
This 32 bit format is not supported by Avid.

**Comment by avaneev** [comment]
You can cast it to uint8_t
