### ISSUE TITLE
Trying to understand.

### ISSUE THREAD

**Issue by ilia3101** [avaneev/avir#24]
Hi I'm trying to understand how the algorithm works. I have some questions...

1. When are 18 taps used: for the initial 2x upscale? Or for the final filter? Or both?
2. What about the correction filter? What does it do/how many taps?
3. How much/why does each filter deviate from a pure sinc?... I'm guessing some/all of them are shortened, to remove ringing artefacts?
4. How can AVIR use 18 taps when lanczos is best with 2 or 3, and gets much worse ringing with 6?
5. When is low pass filtering done? Is it a part of the 2x upscale? Or during the subsequent downscale? Why?
6. Also what is the "Peaked Cosine" window? I can't find any information about it. Is it similar to blackman?

**Comment by avaneev** [comment]
Please look at buildFilterSteps() function. Low-pass filter can be combined with the interpolation filter, depending on the overhead calculation ("modeling"). Low-pass filtering is a part of 2x upscale (on upsize). "Peaked Cosine" is my own windowing function. Filters do not deviate from sinc function, they are sinc-function based, with windowing applied. It's the steep low-pass filters that cause ringing. "Lanczos" is both interpolation and low-pass filter.

**Comment by avaneev** [comment]
By the way, Lanczos3 has 6 taps, not 2 or 3.

**Comment by avaneev** [comment]
6 taps on upsizing. On downsizing Lanczos depends on the resize factor as well, so it is 12 on 2x downsizing, and 24 on 4x downsizing, etc.
