### ISSUE TITLE
affine transform

### ISSUE THREAD

**Issue by aliushn** [avaneev/avir#4]
Thanks  for your work. Would you add rotation function in the toolkit ? such as  affinetransform.

**Comment by avaneev** [comment]
This is not planned, because it would be too complicated with the filters AVIR uses. Considering AVIR's upsizing is quite fast, an option would be to upsize image by 8 and then use linear interpolation to perform any linear (affine) or even non-linear transforms, then downsize by 8.

**Comment by aliushn** [comment]
I see.  Thanks  : )
