### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by bkaradzic** [avaneev/avir#5]
I just ran into this project, but immediately got turned off by custom license. Any license requires some lawyer involvement, but custom licenses are the most difficult to adopt.

Could you consider changing it to something that's widely used?
https://opensource.org/licenses/category

This is up to you, but if I may suggest permissive licesnse like MIT, BSD, or Apache. :)
https://en.wikipedia.org/wiki/Permissive_software_licence

Thanks!

**Comment by avaneev** [comment]
At this time I cannot afford offering another license. If your project is strictly non-commercial, and no party in your project's usage chain may have a profit, you can use AVIR right away. Otherwise we may discuss a custom commercial license.

**Comment by avaneev** [comment]
I've released it under MIT license after all.
