### ISSUE TITLE
Can't compile SSE version with MSVC

### ISSUE THREAD

**Issue by reFX-Mike** [avaneev/avir#7]
It seems you're using MMX intrinsics that can't be used within 64-bit code. You would need to use the SSE equivalents. Can you fix it?

**Comment by avaneev** [comment]
We do not use MMX intrinsics, only SSE2 and AVX. What kind of problem do you experience?
Which compiler error do you get? I've tested AVIR code, it compiles well in 64-bit mode with Intel
C++ compiler and GCC.

**Comment by reFX-Mike** [comment]
You are using MMX instructions:

In avir_float4_sse.h at line 282-293:

```
inline float4 round( const float4& v )
{
    unsigned int prevrm = _MM_GET_ROUNDING_MODE();
    _MM_SET_ROUNDING_MODE( _MM_ROUND_NEAREST );

    const __m128 res = _mm_cvtpi32x2_ps( _mm_cvtps_pi32( v.value ),
        _mm_cvtps_pi32( _mm_movehl_ps( v.value, v.value )));

    _MM_SET_ROUNDING_MODE( prevrm );

    return( res );
}
```

If you replace that whole function with just a single

```
inline float4 round( const float4& v )
{
    return _mm_round_ps ( v.value, _MM_ROUND_NEAREST );
}
```

Then it's SSE and compiles just fine everywhere.

Then you have two template functions that both call "_mm_empty", which is an MMX function.

Both can be removed completely (I've left the functions there, but their body is empty. Then the code compiles and runs just fine.

Please fix ASAP.

**Comment by avaneev** [comment]
Sorry to tell it, but _mm_round_ps is SSE4.1 feature, so I can't include it without breaking SSE-SSE2 compatibility. float4 round() uses only SSE features.

I will remove _mm_empty() though as it is indeed an MMX feature which may be outdated. It helped however in older compilers to overcome some floating point bugs.

**Comment by avaneev** [comment]
As per Intel intrinsic documentation, _mm_round_ps requires ( _MM_FROUND_TO_NEAREST_INT | _MM_FROUND_NO_EXC ) constants which are not available in xmmintrin.h. Also _mm_round_ps works a bit slower than my version.

**Comment by avaneev** [comment]
I have found another variant of rounding function which only uses SSE2 features, and is quite fast. Please check the updated code.

**Comment by reFX-Mike** [comment]
Code compiles and runs fine now.

Still a suggestion to make it even faster: right now the SSE-round function is only used in the dither function. Would it not be *much* faster to set the rounding before in inner loop in the dither function, then just use the round function and reset the rounding back to its old mode after the inner loop?

The round function could then only be:

```
return _mm_cvtepi32_ps( _mm_cvtps_epi32( v.value ));
```

You could even get away with setting/resetting the rounding mode only once per image-resize operation instead of per scan-line.

**Comment by avaneev** [comment]
This does not give any measurable benefit, at max it's only 0.5% faster overall, not worth it.

**Comment by reFX-Mike** [comment]
Really? Isn't setting the rounding-mode expensive and flushing the SSE registers etc.?

**Comment by avaneev** [comment]
I've measured it - almost no benefit with 1920x1080 output image size.

**Comment by reFX-Mike** [comment]
Surprising. Thanks :)
