### ISSUE TITLE
Blend2D support

### ISSUE THREAD

**Issue by Ptomaine** [avaneev/avir#9]
Hello Aleksey,

I have a question regarding how to use your scaling algorithm with Blend2D library: [https://github.com/blend2d/blend2d](https://github.com/blend2d/blend2d)

The Blend2D API provides a way to use custom-defined windowing functions to use for scaling like Lanczos, Blackman and many more.
Could you please guide me how to involve your library properly to provide a windowing function that does scaling using your algorithm?

Thanks,
Arlen.

**Comment by avaneev** [comment]
This may not be possible as filters in AVIR are specially tuned and require internal 2X upsampling, it's a non-conventional approach.

**Comment by Ptomaine** [comment]
Okay. Thanks for the clarification!
